name: CI/CD - Deploy ForFit

on:
  push:
    branches:
      - main # produção
      # - staging  # futuro

jobs:
  deploy:
    name: Deploy Produção
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Limpar bin antigo
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: rm -f /root/ecommerce-white-label-backend/bin/application

      - name: Build com Make
        run: make build

      - name: Enviar binário via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "bin/application"
          target: "/root/ecommerce-white-label-backend/bin"
          strip_components: 1 # <- REMOVE o "bin/" do caminho
          overwrite: true
          debug: true

      - name: Verificar se bin/application existe
        run: |
          ls -lah bin/
          file bin/application || echo "Arquivo não encontrado"

      - name: Reiniciar serviço
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            systemctl daemon-reexec
            systemctl daemon-reload
            systemctl restart forfit
